In [9]:
import numpy as np
from numpy.random import randn

import pandas as pd
from pandas import DataFrame, Series

import matplotlib.pyplot as plt
import seaborn as sns

## Basic Nmupy Operations

In [10]:
np.set_printoptions(precision=2) #2 decimal places

In [6]:
print(f'{rand():.2f}')

0.57


In [ ]:
randn(50)

array([-0.44, -0.24, -0.02, -0.57,  1.98,  0.13, -0.55,  0.05, -1.75,
        0.07,  0.17,  1.11,  0.31, -1.61, -1.85,  1.37,  0.58, -0.28,
        1.06, -0.38,  0.89,  1.49, -1.69, -0.45,  0.01,  2.07, -0.14,
        0.23, -0.28, -0.46, -0.6 , -1.73,  1.7 ,  0.31, -0.47,  0.09,
       -0.03, -0.79,  1.06, -0.58,  0.06,  0.15, -0.2 ,  0.02,  0.94,
        1.27, -0.44, -0.84,  0.51,  2.15])

In [16]:
d = np.arange(1,35)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [19]:
c = np.arange(1,20)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [17]:
d*10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260,
       270, 280, 290, 300, 310, 320, 330, 340])

In [18]:
d+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36])

# EDA

patient. Descriptive statistics provide a quantitative summary of a variable and the data points that comprise it. You can use them to get an understanding of a variable and the attributes that it represents. There are two categories of descriptive statistics. One is descriptive statistics that describe the values of an observation in a variable. And the second is the descriptive statistics that describe a variable's spread. So to get more specific, if you wanted to generate descriptive statistics that describe the observations in a variable then what you would do is you'd go ahead and calculate the sum, median, mean, and max of those observations in the variable. But again, the second way to generate descriptive statistics is to describe the variable's spread. And if you wanted to do that what you would to is calculate out standard deviation, variance, counts or quartiles. If this doesn't make a lot of sense to you now just hold on, because I'm going to show you an example on the coding demonstration and then you'll really understand what I'm talking about. But first let's look at some of the uses for descriptive statistics. You can use descriptive statistics to easily detect outliers. You can use it for planning data preparation requirements for machine learning, and you could use it for selecting features for use in machine learning. Okay, so now let me show you how to generate summary statistics using pandas and scipy. We're going to start off, of course, by bringing in our libraries. So we need to to import numpy, pandas, series and data frame and then also scipy. I want to point out that we are importing stats from scipy. And I've got these already loaded for you in the Jupiter notebook and your notebook's also coming preloaded with the MT car's data set just to save you time so you can just go ahead and run these. We've already covered these in previous lectures. And what I'd like to do first is just to print