In [35]:
import torch
import numpy as np

A tensor contains elements of a single data type.  
When dealing with real numbers, the tensor type could either be a float tensor or a double tensor.

When dealing with unsigned integers that are used in 8 bit images, the tensor type is a byte tensor.

In [3]:
a0 = torch.tensor([0, 1, 3, 4])
a0.dtype

torch.int64

In [4]:
a0[0]

tensor(0)

In [12]:
#to set type
a1 = torch.tensor([0, 1, 3, 4], dtype=torch.int32)
a1.dtype, a1.type() 

(torch.int32, 'torch.IntTensor')

In [11]:
a2 = torch.tensor([0, 1, 3, 4], dtype=torch.float32)
a2.type()

'torch.FloatTensor'

In [7]:
a2

tensor([0., 1., 3., 4.])

In [8]:
a2_2 = torch.FloatTensor([0,1,2,3])
a2_2.dtype

torch.float32

In [9]:
a2_2

tensor([0., 1., 2., 3.])

In [13]:
a1.type()

'torch.IntTensor'

In [14]:
a1 = a1.type(torch.FloatTensor)

In [15]:
a1.dtype

torch.float32

In [16]:
a1.size()

torch.Size([4])

In [17]:
#Rank or dimension
a1.ndimension()

1

In [19]:
a11 = torch.Tensor([[1,2],[3,4]])

a11.size(), a11.ndimension()

(torch.Size([2, 2]), 2)

**Converting 1d to 2d**

In [20]:
a1_col = a1.view(4,1)
a1_col

tensor([[0.],
        [1.],
        [3.],
        [4.]])

In [23]:
a1_col.ndim

2

In [25]:
a1_col.size()

torch.Size([4, 1])

In [26]:
#if num of elements is unknown
a1.view(-1,1) #-1 --> num of elements as rows, 1 column

tensor([[0.],
        [1.],
        [3.],
        [4.]])

In [34]:
a1.view(-1,1,1)

tensor([[[0.]],

        [[1.]],

        [[3.]],

        [[4.]]])

**From - to numpy array**

In [46]:
arr = np.array([0,1,2,3])
arr

array([0, 1, 2, 3])

In [47]:
tensor_arr = torch.from_numpy(arr)
tensor_arr

tensor([0, 1, 2, 3], dtype=torch.int32)

In [48]:
back_numpy = tensor_arr.numpy()
back_numpy

array([0, 1, 2, 3])

In [49]:
back_numpy[2]

2

In [50]:
arr[2]= 10

In [51]:
tensor_arr[2]

tensor(10, dtype=torch.int32)

In [52]:
back_numpy[2]

10

In [ ]:
tensor_df = torch.from_numpy(series.values)

In [53]:
list_tensor = tensor_arr.tolist()
list_tensor

[0, 1, 10, 3]

In [54]:
list_tensor[1]=45
tensor_arr

tensor([ 0,  1, 10,  3], dtype=torch.int32)

In [55]:
list_tensor, tensor_arr, back_numpy, arr

([0, 45, 10, 3],
 tensor([ 0,  1, 10,  3], dtype=torch.int32),
 array([ 0,  1, 10,  3]),
 array([ 0,  1, 10,  3]))

In [56]:
arr[1]=55

In [57]:
list_tensor, tensor_arr, back_numpy, arr

([0, 45, 10, 3],
 tensor([ 0, 55, 10,  3], dtype=torch.int32),
 array([ 0, 55, 10,  3]),
 array([ 0, 55, 10,  3]))

**Note that individual values of a tensor are also tensors.**

In [58]:
tensor_arr[0]

tensor(0, dtype=torch.int32)

In [59]:
#to return number
tensor_arr[0].item()

0

### Basic Operations

In [68]:
u = torch.tensor([1, 0], dtype=torch.int32)
v = torch.tensor([0, 1], dtype=torch.int32)

In [69]:
u.dtype

torch.int32

In [70]:
z = u+v
z

tensor([1, 1], dtype=torch.int32)

In [79]:
u+1

tensor([2, 1], dtype=torch.int32)

In [71]:
u*v

tensor([0, 0], dtype=torch.int32)

In [72]:
y= v*2
y

tensor([0, 2], dtype=torch.int32)

In [74]:
#for dot product
torch.dot(u,v)

tensor(0, dtype=torch.int32)

In [80]:
u.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Int

In [83]:
u.type(torch.float32).mean()

tensor(0.5000)

In [84]:
u.max()

tensor(1, dtype=torch.int32)

In [85]:
x = torch.tensor([0, np.pi/2, np.pi])
y= torch.sin(x)

In [86]:
x

tensor([0.0000, 1.5708, 3.1416])

In [87]:
y

tensor([ 0.0000e+00,  1.0000e+00, -8.7423e-08])

In [92]:
torch.linspace(0,10, steps = 5, dtype = torch.int)

tensor([ 0,  2,  5,  7, 10], dtype=torch.int32)

In [93]:
torch.linspace(0,2*np.pi, steps = 10,)

tensor([0.0000, 0.6981, 1.3963, 2.0944, 2.7925, 3.4907, 4.1888, 4.8869, 5.5851,
        6.2832])